### ISSUE TITLE
Get our bluetooth hardware

### ISSUE THREAD

**Issue by leohentschker** [leohentschker/village-reach#6]
It turns out that the only Raspberry Pi model with native support for BLE is the Raspberry Pi 3. Annoyingly, this means any Raspberry Pis that we have that aren't 3s aren't going to be that helpful in terms of testing. This means that we are going to need to get 2 Raspberry Pi3s before we can make meaningful progress.

**Comment by leohentschker** [comment]
Class 1 [Bluetooth dongle](https://www.startech.com/Networking-IO/Bluetooth-Telecom/USB-Bluetooth-4-Dongle~USBBT1EDR4
)

**Comment by Ivraj** [comment]
@leohentschker are you going to be ordering that dongle? Otherwise, I can take care of the order as well.

**Comment by leohentschker** [comment]
@Ivraj I spoke with Konrad and he mentioned ordering it with the D4D budget. I'll email him to ask how that went. If that's going to take any more than two days I'll just order them myself.
